name: Enforce Target Reviewer Only

on:
  pull_request_review:
    types: [submitted]

jobs:
  allow-only-target-reviewer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up GitHub CLI
      run: sudo apt-get install gh -y

    - name: Fetch old and new file for analysis
      run: |
        mkdir files
        git fetch origin ${{ github.event.pull_request.base.ref }}
        git fetch origin ${{ github.event.pull_request.head.ref }}
        git show origin/${{ github.event.pull_request.base.ref }}:test.txt > files/old.txt || echo "" > files/old.txt
        git show origin/${{ github.event.pull_request.head.ref }}:test.txt > files/new.txt || echo "" > files/new.txt

    - name: Run test.py to get target user
      run: |
        python3 test.py files/old.txt files/new.txt > output.txt
        TARGET_USER=$(cat output.txt)
        echo "TARGET_USER=$TARGET_USER" >> $GITHUB_ENV

    - name: Check if reviewer is the target
      run: |
        REVIEWER="${{ github.event.review.user.login }}"
        echo "Review submitted by: $REVIEWER"
        echo "Expected reviewer (target): $TARGET_USER"

        if [ "$REVIEWER" != "$TARGET_USER" ]; then
          echo "❌ Unauthorized reviewer: $REVIEWER"
          gh pr comment ${{ github.event.pull_request.number }} \
            --body ":no_entry: Only @${TARGET_USER} is allowed to approve this PR. @${REVIEWER}'s approval is not valid."

          # Fail the job so this PR can't pass checks
          exit 1
        else
          echo "✅ Valid approver: $REVIEWER"
        fi

      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
